workflows:
  hello-world:
    name: Hello world workflow
    scripts:
      - echo "Hello World!"
  daily-trunk:
    name: Daily trunk build
    scripts:
      - echo "Daily trunk build success!"
  print-env:
    name: Print env variables
    scripts:
      - name: print env script
        script: |
          #!/bin/sh
          set -ex
          printenv
  set-env-runtime:
    name: Setting environment variables during the build
    scripts:
      - name: set env var
        script: |
          echo "KEY=test value" >> $CM_ENV
      - name: use env var
        script: |
          echo $KEY
  build-PR:
    name: PR build
    instance_type: linux
    environment:
      groups:
        - keystore_credentials
      vars:
        PUBLIC_ENV_VAR: "value here"
      java: 11
    scripts:
      - &echo_build_info
        name: Script name
        script: echo "PR build success!"
      - *echo_build_info
      - *echo_build_info